apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-flask-app
  name: flask-app-deployment-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
      version: canary
  template:
    metadata:
      labels:
        app: my-flask-app
        version: canary
    spec:
      containers:
      - name: my-flask-app-container-canary
        image: my-flask-app-image:canary
        ports:
        - containerPort: 5500
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
